version: '3'
services:
  nginx:
    image: nginx:stable
    ports:
      - 80:80
    volumes:
      # Nginx has access to the public folder only.
      - ./public:/var/www/html/public
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fpm
  fpm:
    image: php:8.1-fpm
    volumes:
      # PHP has access to the full project.
      - .:/var/www/html
